// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module top (
        input wire clk,
        input wire rst,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [4:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input top_pkg::top__in_t hwif_in,
        output top_pkg::top__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [4:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(rst) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[4:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end
    assign cpuif_wr_biten = '1;

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic CTRL;
        logic TEST;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.CTRL = cpuif_req_masked & (cpuif_addr == 5'h0);
        decoded_reg_strb.TEST = cpuif_req_masked & (cpuif_addr == 5'h10);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } ENABLE;
            struct {
                logic next;
                logic load_next;
            } FLAG;
            struct {
                logic [1:0] next;
                logic load_next;
            } RESET_ALL;
        } CTRL;
        struct {
            struct {
                logic next;
                logic load_next;
            } FLAG;
        } TEST;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } ENABLE;
            struct {
                logic value;
            } FLAG;
            struct {
                logic [1:0] value;
            } RESET_ALL;
        } CTRL;
        struct {
            struct {
                logic value;
            } FLAG;
        } TEST;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: top.CTRL.ENABLE
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.ENABLE.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.CTRL.ENABLE.value & ~(decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.CTRL.ENABLE.next;
            load_next_c = '1;
        end
        field_combo.CTRL.ENABLE.next = next_c;
        field_combo.CTRL.ENABLE.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CTRL.ENABLE.value <= 1'h1;
        end else begin
            if(field_combo.CTRL.ENABLE.load_next) begin
                field_storage.CTRL.ENABLE.value <= field_combo.CTRL.ENABLE.next;
            end
        end
    end
    assign hwif_out.CTRL.ENABLE.value = field_storage.CTRL.ENABLE.value;
    // Field: top.CTRL.FLAG
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.FLAG.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CTRL.FLAG.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end else if(hwif_in.CTRL.FLAG.we) begin // HW Write - we
            next_c = hwif_in.CTRL.FLAG.next;
            load_next_c = '1;
        end
        field_combo.CTRL.FLAG.next = next_c;
        field_combo.CTRL.FLAG.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CTRL.FLAG.value <= 1'h0;
        end else begin
            if(field_combo.CTRL.FLAG.load_next) begin
                field_storage.CTRL.FLAG.value <= field_combo.CTRL.FLAG.next;
            end
        end
    end
    assign hwif_out.CTRL.FLAG.value = field_storage.CTRL.FLAG.value;
    // Field: top.CTRL.RESET_ALL
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.RESET_ALL.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.CTRL.RESET_ALL.value & ~(decoded_wr_data[3:2] & decoded_wr_biten[3:2]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.CTRL.RESET_ALL.next;
            load_next_c = '1;
        end
        field_combo.CTRL.RESET_ALL.next = next_c;
        field_combo.CTRL.RESET_ALL.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CTRL.RESET_ALL.value <= 2'h0;
        end else begin
            if(field_combo.CTRL.RESET_ALL.load_next) begin
                field_storage.CTRL.RESET_ALL.value <= field_combo.CTRL.RESET_ALL.next;
            end
        end
    end
    assign hwif_out.CTRL.RESET_ALL.value = field_storage.CTRL.RESET_ALL.value;
    // Field: top.TEST.FLAG
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.TEST.FLAG.value;
        load_next_c = '0;
        if(decoded_reg_strb.TEST && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.TEST.FLAG.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else if(hwif_in.TEST.FLAG.we) begin // HW Write - we
            next_c = hwif_in.TEST.FLAG.next;
            load_next_c = '1;
        end
        field_combo.TEST.FLAG.next = next_c;
        field_combo.TEST.FLAG.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.TEST.FLAG.value <= 1'h0;
        end else begin
            if(field_combo.TEST.FLAG.load_next) begin
                field_storage.TEST.FLAG.value <= field_combo.TEST.FLAG.next;
            end
        end
    end
    assign hwif_out.TEST.FLAG.value = field_storage.TEST.FLAG.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[2];
    assign readback_array[0][0:0] = (decoded_reg_strb.CTRL && !decoded_req_is_wr) ? field_storage.CTRL.ENABLE.value : '0;
    assign readback_array[0][1:1] = (decoded_reg_strb.CTRL && !decoded_req_is_wr) ? field_storage.CTRL.FLAG.value : '0;
    assign readback_array[0][3:2] = (decoded_reg_strb.CTRL && !decoded_req_is_wr) ? field_storage.CTRL.RESET_ALL.value : '0;
    assign readback_array[0][31:4] = '0;
    assign readback_array[1][0:0] = (decoded_reg_strb.TEST && !decoded_req_is_wr) ? field_storage.TEST.FLAG.value : '0;
    assign readback_array[1][31:1] = '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<2; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
