// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package top_pkg;

    localparam TOP_DATA_WIDTH = 32;
    localparam TOP_MIN_ADDR_WIDTH = 5;
    localparam TOP_SIZE = 'h14;

    typedef struct {
        logic next;
    } top__CTRL__ENABLE__in_t;

    typedef struct {
        logic next;
        logic we;
    } top__CTRL__FLAG__in_t;

    typedef struct {
        logic [1:0] next;
    } top__CTRL__RESET_ALL__in_t;

    typedef struct {
        top__CTRL__ENABLE__in_t ENABLE;
        top__CTRL__FLAG__in_t FLAG;
        top__CTRL__RESET_ALL__in_t RESET_ALL;
    } top__CTRL__in_t;

    typedef struct {
        logic next;
        logic we;
    } top__TEST__FLAG__in_t;

    typedef struct {
        top__TEST__FLAG__in_t FLAG;
    } top__TEST__in_t;

    typedef struct {
        top__CTRL__in_t CTRL;
        top__TEST__in_t TEST;
    } top__in_t;

    typedef struct {
        logic value;
    } top__CTRL__ENABLE__out_t;

    typedef struct {
        logic value;
    } top__CTRL__FLAG__out_t;

    typedef struct {
        logic [1:0] value;
    } top__CTRL__RESET_ALL__out_t;

    typedef struct {
        top__CTRL__ENABLE__out_t ENABLE;
        top__CTRL__FLAG__out_t FLAG;
        top__CTRL__RESET_ALL__out_t RESET_ALL;
    } top__CTRL__out_t;

    typedef struct {
        logic value;
    } top__TEST__FLAG__out_t;

    typedef struct {
        top__TEST__FLAG__out_t FLAG;
    } top__TEST__out_t;

    typedef struct {
        top__CTRL__out_t CTRL;
        top__TEST__out_t TEST;
    } top__out_t;
endpackage
